"""Stage E end-to-end: build a real project and render a real MP4.

This is the deliverable from directive sections 70-71, 73-74 and 91.  It builds
``StageE_Test`` with real content - narration, a music bed, a sound effect,
subtitles, transitions, an animation, an image and a chart plus a number - then
renders it twice and verifies both files with the real probe and the QC service.

Nothing here is mocked.  If narration cannot be generated by Kokoro (no model
weights on this machine), the script says so loudly and falls back to real audio
files of a measured length, so the render is still a real render - and the
report marks the narration as synthetic rather than passing it off as Kokoro.

Usage::

    python scripts/stage_e_end_to_end.py --data-root /tmp/stage_e
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.paths import AppPaths                                        # noqa: E402
from app.core.settings import Settings                                    # noqa: E402
from app.media.probe import probe_media                                   # noqa: E402
from app.project.model import (                                           # noqa: E402
    AssetSpec,
    ElementSpec,
    ScriptSection,
    SoundEffect,
)
from app.project.service import CreateRequest, ProjectService             # noqa: E402
from app.render import RenderEngine, RenderRequest                        # noqa: E402
from app.scene.templates import create_scene_from_template, default_templates_registered  # noqa: E402
from app.tools.ffmpeg import FFmpegTools, discover_ffmpeg                 # noqa: E402

WIDTH, HEIGHT, FPS = 1280, 720, 30

SCENES = [
    {
        "id": "s1", "name": "Opening title", "template": "title",
        "content": {"title": "Motion Graphics Studio", "subtitle": "Stage E end to end"},
        "text": "Welcome. This video was rendered end to end by the Stage E pipeline.",
        "transition": "fade",
    },
    {
        "id": "s2", "name": "Product image", "template": "image",
        "content": {"text": "A real imported image, fitted without stretching."},
        "text": "Scenes can carry imported images, charts, numbers and text.",
        "transition": "slide",
    },
    {
        "id": "s3", "name": "Quarterly chart", "template": "chart",
        "content": {"title": "Renders per quarter",
                    "values": [12, 30, 18, 44, 27],
                    "labels": ["Q1", "Q2", "Q3", "Q4", "Q5"]},
        "text": "Charts are laid out responsively at whatever resolution you export.",
        "transition": "wipe",
    },
    {
        "id": "s4", "name": "Closing number", "template": "stat",
        "content": {"title": "Scenes rendered", "value": 4, "unit": "scenes"},
        "text": "That is the whole pipeline, from script to a verified MP4 file.",
        "transition": "none",
    },
]


def _log(message: str) -> None:
    print(message, flush=True)


def _tone(tools: FFmpegTools, path: Path, seconds: float, frequency: int,
          channels: int = 1) -> Path:
    """A real audio file of a known length."""
    path.parent.mkdir(parents=True, exist_ok=True)
    result = tools.run([
        "-hide_banner", "-loglevel", "error", "-y",
        "-f", "lavfi", "-i", f"sine=frequency={frequency}:duration={seconds}",
        "-ar", "48000", "-ac", str(channels), str(path),
    ], timeout=180.0)
    if not result.ok:
        raise RuntimeError(f"Could not create {path.name}: {result.describe_failure()}")
    return path


def _placeholder_image(path: Path, width: int = 960, height: int = 540) -> Path:
    """A real PNG, so the image scene renders an actual picture."""
    from PIL import Image, ImageDraw

    path.parent.mkdir(parents=True, exist_ok=True)
    image = Image.new("RGB", (width, height), "#1d2433")
    draw = ImageDraw.Draw(image)
    for index in range(0, width, 60):
        draw.line([(index, 0), (index, height)], fill="#2a3447", width=2)
    draw.rectangle([40, 40, width - 40, height - 40], outline="#7fb2ff", width=6)
    draw.text((60, height // 2), "imported image asset", fill="#e8eefc")
    image.save(path)
    return path


def _md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def build_project(service: ProjectService, tools: FFmpegTools) -> tuple[object, dict, Path]:
    """Create the StageE_Test project with real content on disk."""
    notes: dict[str, str] = {}

    project = service.create_project(CreateRequest(
        name="StageE_Test", description="Stage E end-to-end render test",
        width=WIDTH, height=HEIGHT, fps=FPS, template="blank"))
    # The folder only exists once the project has been created.
    project_dir = Path(service.session.layout.root)

    # -- a real image asset ------------------------------------------------
    image_path = _placeholder_image(project_dir / "assets" / "product.png")
    from PIL import Image

    with Image.open(image_path) as picture:
        size = picture.size
    asset = AssetSpec(id="product_image", name="Product image", kind="image",
                      path="assets/product.png", size_bytes=image_path.stat().st_size,
                      width=size[0], height=size[1])
    project.assets.append(asset)

    # -- scenes, script sections and transitions ---------------------------
    default_templates_registered()
    project.scenes.clear()
    for index, spec in enumerate(SCENES):
        scene = create_scene_from_template(spec["template"], dict(spec["content"]))
        scene.id = spec["id"]
        scene.name = spec["name"]
        scene.narration.text = spec["text"]
        if spec["transition"] != "none" and index + 1 < len(SCENES):
            scene.transition_out.type = spec["transition"]
            scene.transition_out.duration = 0.5
            next_scene_kind = SCENES[index + 1]["transition"]
            if next_scene_kind != "none":
                scene.transition_out.type = SCENES[index]["transition"]
        project.scenes.append(scene)
        project.script.sections.append(ScriptSection(
            id=f"sec{index + 1}", title=spec["name"], text=spec["text"], order=index + 1))

    for scene, following in zip(project.scenes, project.scenes[1:]):
        following.transition_in.type = scene.transition_out.type
        following.transition_in.duration = scene.transition_out.duration

    # An explicit animation on the first scene, so motion is really rendered.
    project.scenes[0].elements.append(ElementSpec(
        id="anim_badge", kind="text", text="animated in",
        position={"x": 0.5, "y": 0.72}, size={"mode": "relative", "value": 0.05},
        animation={"preset": "slide up"}, color="#9fd0ff"))

    # Point the image scene at the real asset.
    for element in project.scenes[1].elements:
        if element.kind == "image":
            element.asset_id = asset.id

    # -- music and one sound effect ---------------------------------------
    music = _tone(tools, project_dir / "audio" / "music.wav", 30.0, 110, channels=2)
    sfx = _tone(tools, project_dir / "audio" / "sfx.wav", 0.6, 880)
    project.audio.music.id = "music_bed"
    project.audio.music.path = "audio/music.wav"
    project.audio.music.volume = 0.22
    project.audio.music.loop = True
    project.audio.music.fade_in = 0.5
    project.audio.music.fade_out = 1.5
    project.audio.sfx.append(SoundEffect(
        id="sfx_ping", path="audio/sfx.wav", volume=0.5, anchor="project",
        at_seconds=0.4, fade_in=0.02, fade_out=0.15))
    notes["music"] = f"{music.name} ({music.stat().st_size} bytes)"
    notes["sfx"] = f"{sfx.name} ({sfx.stat().st_size} bytes)"

    # -- subtitles and export settings ------------------------------------
    project.subtitles.enabled = True
    project.subtitles.language = "en"
    project.narration.mode = "section_scene"
    project.format.width, project.format.height, project.format.fps = WIDTH, HEIGHT, FPS
    project.format.quality_preset = "high"
    project.format.encoder_preset = "veryfast"
    project.format.crf = 26
    project.export.output_dir = "renders"
    # The directive names the deliverables StageE_Test_Video1.mp4 and _Video2,
    # so the template is set to match rather than left at the default.
    project.export.filename_template = "{name}_Video{seq}"
    return project, notes, project_dir


def generate_narration(project, project_dir: Path, tools: FFmpegTools) -> str:
    """Real Kokoro narration when the model is present; disclosed fallback otherwise."""
    from app.tts.capabilities import probe_kokoro
    from app.tts.narration import NarrationSettings, attach_narration_to_scenes, generate_narration

    status = probe_kokoro(deep_init_check=True)
    if status.ready:
        outcome = generate_narration(project, project_dir, NarrationSettings(), overwrite=True)
        if outcome.ok:
            notes = attach_narration_to_scenes(project, outcome.tracks)
            _log(f"Narration: real Kokoro ({outcome.summary()})")
            for note in notes:
                _log(f"  {note}")
            return "kokoro"
        _log(f"Kokoro was ready but generation failed: {outcome.summary()}")
        _log("Falling back to synthetic narration of a measured length.")

    # -- disclosed fallback ------------------------------------------------
    _log("Narration: SYNTHETIC - Kokoro could not run on this machine.")
    for problem in status.problems[:2]:
        _log(f"  reason: {problem}")
    _log("  Real WAV files of a measured length are used instead, so the render")
    _log("  and every timing check are still real. Kokoro is exercised by the")
    _log("  Stage C tests; it needs model weights this machine does not have.")

    from app.tts.narration import attach_narration_to_scenes
    from app.project.model import NarrationTrack

    tracks = []
    for index, scene in enumerate(project.scenes, start=1):
        length = 2.0 + 0.35 * index
        path = project_dir / "audio" / "narration" / f"narration_scene_{index:03d}.wav"
        _tone(tools, path, length, 180 + index * 40)
        info = probe_media(path, tools)
        track = NarrationTrack(
            id=f"track{index}", kind="section",
            section_id=f"sec{index}", path=f"audio/narration/{path.name}",
            status="ready", actual_duration_seconds=info.duration or length,
            sample_rate=info.sample_rate or 48000, channels=info.channels or 1,
            size_bytes=path.stat().st_size)
        project.narration.tracks.append(track)
        tracks.append(track)
    for note in attach_narration_to_scenes(project, tracks):
        _log(f"  {note}")
    return "synthetic"


def verify(path: Path, tools: FFmpegTools, *, expected_duration: float,
           expect_audio: bool, quick: bool = False) -> dict:
    """Probe and QC one finished file."""
    from app.render.qc import QCService

    info = probe_media(path, tools)
    report = QCService(tools, deep_checks=not quick).check(
        path, expected_duration=expected_duration, expected_width=WIDTH,
        expected_height=HEIGHT, expected_fps=FPS, expect_audio=expect_audio)
    return {"info": info, "report": report}


def render_once(project, project_dir: Path, tools: FFmpegTools, label: str) -> object:
    last = {"percent": -1}

    def show(progress):
        bucket = int(progress.percent // 10) * 10
        if bucket != last["percent"]:
            last["percent"] = bucket
            _log(f"    {progress.state:<10} {progress.percent:5.1f}%  {progress.message}")

    _log(f"\n--- {label} ---")
    return RenderEngine(tools, project_dir=project_dir, progress=show).render(
        RenderRequest(project=project, quick_qc=False))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", default="/tmp/stage_e")
    args = parser.parse_args(argv)

    root = Path(args.data_root)
    if root.exists():
        shutil.rmtree(root)
    paths = AppPaths(data_root=root, source_root=Path(__file__).resolve().parent.parent,
                     reason="stage-e-e2e")
    paths.ensure()
    discovery = discover_ffmpeg()
    if not discovery.has_ffmpeg:
        _log("FFmpeg is not installed, so nothing can be rendered.")
        return 2
    tools = FFmpegTools(discovery)
    _log(f"FFmpeg {discovery.ffmpeg.version if discovery.ffmpeg else ''}")

    service = ProjectService(paths, Settings())
    project, notes, project_dir = build_project(service, tools)
    _log(f"Project folder: {project_dir}")
    for key, value in notes.items():
        _log(f"  {key}: {value}")

    narration_kind = generate_narration(project, project_dir, tools)
    service.save()

    from app.scene.timing import build_timeline

    timeline = build_timeline(project.scenes)
    _log(f"\nTimeline: {timeline.total_duration:.2f}s across {timeline.scene_count} scene(s)")
    for timing in timeline.timings:
        _log(f"  {timing.name:<18} {timing.start:6.2f} -> {timing.end:6.2f}  "
             f"({timing.source}, {timing.transition_out})")

    # -- first render ------------------------------------------------------
    first = render_once(project, project_dir, tools, "Render 1")
    if not first.ok:
        _log(f"\nRender 1 failed: {first.message}")
        if first.what_to_do:
            _log(f"What to do: {first.what_to_do}")
        for error in first.errors:
            _log(f"  [{getattr(error, 'code', '?')}] {getattr(error, 'message', error)}")
        return 1
    checked_1 = verify(first.path, tools, expected_duration=timeline.total_duration,
                       expect_audio=True)

    # -- second render -----------------------------------------------------
    second = render_once(project, project_dir, tools, "Render 2")
    if not second.ok:
        _log(f"\nRender 2 failed: {second.message}")
        return 1
    checked_2 = verify(second.path, tools, expected_duration=timeline.total_duration,
                       expect_audio=True)

    untouched = _md5(first.path) == _md5(first.path) and first.path.exists()
    separate = first.path != second.path and second.path.exists()

    # -- report ------------------------------------------------------------
    _log("\n" + "=" * 70)
    _log("STAGE E END-TO-END RESULT")
    _log("=" * 70)
    for label, result, checked in (("Video1", first, checked_1),
                                   ("Video2", second, checked_2)):
        info = checked["info"]
        report = checked["report"]
        _log(f"\n{label}: {result.path}")
        _log(f"  status     : {result.status}")
        _log(f"  resolution : {info.width}x{info.height}")
        _log(f"  fps        : {info.fps}")
        _log(f"  duration   : {info.duration:.2f}s (timeline {timeline.total_duration:.2f}s)")
        _log(f"  video      : {info.video_codec} {info.pixel_format}")
        _log(f"  audio      : {info.audio_codec} {info.sample_rate} Hz {info.channels} ch")
        _log(f"  size       : {info.size_bytes:,} bytes")
        _log(f"  QC         : {report.verdict}")
        for issue in report.issues:
            _log(f"      [{issue.severity}] {issue.code}: {issue.message}")

    _log(f"\nNarration source        : {narration_kind}")
    _log(f"Video1 untouched        : {untouched}")
    _log(f"Video2 is a new file    : {separate}")
    _log(f"Subtitles generated     : {first.details.get('subtitle_count', 0)} cue(s)")
    _log(f"Subtitle side-car files : {first.details.get('subtitle_files')}")
    _log(f"Segments rendered       : {first.details.get('segments')}")
    _log(f"Frames                  : {first.details.get('frames')}")
    _log(f"Render 1 took           : {first.seconds:.1f}s")
    _log(f"Render 2 took           : {second.seconds:.1f}s")

    ok = (first.ok and second.ok and untouched and separate
          and not checked_1["report"].has_fail and not checked_2["report"].has_fail)
    _log(f"\nOVERALL: {'PASS' if ok else 'FAIL'}")

    # The two states the Stage E gate requires, kept distinct.
    from app.tts.selftest import NOT_VERIFIED, VERIFIED

    if narration_kind == "kokoro":
        _log(f"PIPELINE VERIFIED.  {VERIFIED}.")
    else:
        _log(f"PIPELINE VERIFIED.  {NOT_VERIFIED}.")
        _log("The render pipeline is verified with explicitly labelled synthetic")
        _log("test narration; the Kokoro runtime path remains unverified on this")
        _log("machine because model weights are unavailable.  There is no cloud or")
        _log("paid voice service behind it.")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
